In [21]:
import numpy as np
import pandas as pd

# Задание 1

In [128]:
rev_array = lambda n: np.arange(n)[::-1]
rev_array(9)

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание 2

In [129]:
np.diag(rev_array(5))

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [130]:
np.diag(rev_array(5)).sum()

10

# Задание 3

In [131]:
ratings = pd.read_csv('ml-latest-small/ratings.csv')
movies = pd.read_csv('ml-latest-small/movies.csv')

In [132]:
only_fives = ratings[ratings['rating'] == 5.0]
res = only_fives.groupby('movieId').count().sort_values('rating', ascending=False).index.tolist()[0]
res

318

In [133]:
movies[movies['movieId'] == res]

movieId                             title       genres
277      318  Shawshank Redemption, The (1994)  Crime|Drama

# Задание 4

In [134]:
power = pd.read_csv('power.csv')

In [135]:
baltic_states = ['Latvia', 'Lithuania', 'Estonia']
category = [4, 12, 21]
time_period = range(2005, 2011)

In [137]:
res = power[
    power['country'].isin(baltic_states) & 
    power['category'].isin(category) & 
    power['year'].isin(time_period) & 
    power['quantity'] > 0]

In [138]:
res['quantity'].sum()

240481.0

# Задание 5

In [139]:
M = [[4, 2, 1], [1, 3, 0], [0, 5, 4]]
v = [4, 12, -3]

In [140]:
np.linalg.solve(M, v)

array([ 0.46666667,  3.84444444, -5.55555556])